### ISSUE TITLE
nextjs-app compilation error and warning

### ISSUE THREAD

**Issue by jtlapp** [belgattitude/nextjs-monorepo-example#2969]
I got this error and warning from the nextjs-app v3.58.0 build:

```
➤ YN0000: [nextjs-app]: info  - Loaded env from /Users/joe/repos/nounzoo/apps/nextjs-app/.env
➤ YN0000: [nextjs-app]: notice- Will transpile [ky]
➤ YN0000: [nextjs-app]: info  - Linting and checking validity of types...
➤ YN0000: [nextjs-app]: warn  - You have enabled experimental features (outputFileTracingRoot, externalDir) in next.config.mjs.
➤ YN0000: [nextjs-app]: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
➤ YN0000: [nextjs-app]: 
➤ YN0000: [nextjs-app]: 
➤ YN0000: [nextjs-app]: Failed to compile.
➤ YN0000: [nextjs-app]: 
➤ YN0000: [nextjs-app]: ./src/backend/graphql/graphqlSchema.ts
➤ YN0000: [nextjs-app]: 4:1  Error: `@nounzoo/db-main-prisma` import should occur before import of `@pothos/core`  import/order
➤ YN0000: [nextjs-app]: 
➤ YN0000: [nextjs-app]: ./src/features/home/blocks/hero/HeroBlock.tsx
➤ YN0000: [nextjs-app]: 10:11  Warning: 't' is assigned a value but never used.  @typescript-eslint/no-unused-vars
➤ YN0000: [nextjs-app]: 
➤ YN0000: [nextjs-app]: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
➤ YN0000: [nextjs-app]: Process exited (exit code 1), completed in 8s 902ms
```

I was able to eliminate the error by moving the following line to the top of the file `graphqlSchema.ts`:

`import type { DbMainPrismaTypes } from '@nounzoo/db-main-prisma';`

And by removing the following two lines from `HeroBlock.tsx`:

`import { useTranslation } from 'next-i18next';`

`  const { t } = useTranslation(['home', 'common']);`

Would you like a pull request?

**Comment by jtlapp** [comment]
I also get the following errors on the git pre-check but not on any builds:

```
/Users/joe/repos/nounzoo/apps/nextjs-app/e2e/api/_monitor/healthcheck.spec.ts
  2:1  error  `@nounzoo/ts-utils` import should occur before import of `@playwright/test`  import/order

/Users/joe/repos/nounzoo/apps/nextjs-app/e2e/api/gateway/graphql.spec.ts
  2:1  error  `@nounzoo/ts-utils` import should occur before import of `@playwright/test`  import/order

/Users/joe/repos/nounzoo/apps/nextjs-app/e2e/pages/index/index.spec.ts
  1:1  error  `@playwright/test` import should occur after import of `@nounzoo/common-i18n/locales/fr/demo.json`  import/order

/Users/joe/repos/nounzoo/apps/nextjs-app/e2e/pages/system/404.spec.ts
  1:1  error  `@playwright/test` import should occur after import of `@nounzoo/common-i18n/locales/fr/system.json`  import/order

✖ 4 problems (4 errors, 0 warnings)
  4 errors and 0 warnings potentially fixable with the `--fix` option.

husky - pre-commit hook exited with code 1 (error)
```

I attempted to re-order the imports, but I continue to get these errors. I tried `yarn g:clean` to no available. It seems like it's pulling from a cache.

**Comment by belgattitude** [comment]
Thanks, actually it's not a bug. By changing `@your-org/db-main-prisma` into `@nounzoo/db-main-prisma`, the enforced order change.

It's enforced in the import/order, see 

https://github.com/belgattitude/nextjs-monorepo-example/blob/38b70a6ce033ad6c524878ef18f87eb893c89e4b/packages/eslint-config-bases/src/bases/typescript.js#L54

Of course it's an example, up to you to decide if you want to have this rule.

Otherwise good tips:

- Command line: `yarn lint --fix` / or globally `yarn g:lint --fix`
- Note that this is done automatically for you when you commit (lint-staged/husky)

And of course you can setup your ide (vscode/webstorm...) to automatically run the linter on save. If you use the example config, it should be done for you: https://github.com/belgattitude/nextjs-monorepo-example/blob/38b70a6ce033ad6c524878ef18f87eb893c89e4b/monorepo.code-workspace#L54

**Comment by jtlapp** [comment]
Okay, thank you. FYI, I've decided to use your monorepo example and another as references for creating my own, as there's more complexity than I'd like at the start of a project. I'd like to extend the solution as I feel the need.
