### ISSUE TITLE
Error: No mesh config file found

### ISSUE THREAD

**Issue by amykhar** [belgattitude/nextjs-monorepo-example#3299]
Steps to reproduce:
1. Clone repo - main branch
2. run yarn docker:nextjs-app:develop

Expected result - images come up with apps.
Actual result: fails with 
`Mesh Error: No mesh config file found in "/workspace-install/packages/api-gateway"!
#0 45.99 ➤ YN0000: │ @your-org/api-gateway@workspace:packages/api-gateway STDOUT     at findAndParseConfig (/workspace-install/node_modules/@graphql-mesh/cli/cjs/config.js:71:15)
#0 45.99 ➤ YN0000: │ @your-org/api-gateway@workspace:packages/api-gateway STDOUT     at async Object.handler (/workspace-install/node_modules/@graphql-mesh/cli/cjs/index.js:291:32)`

OS: MacOS Ventura 13.1
Macbook Air M1

**Comment by belgattitude** [comment]
Hello @amykhar ... thx for reporting

Haven't maintained the docker as it should, have to admit I learned so much since that I'm not sure I would do it the same as it is.

That said there some possibles in https://github.com/belgattitude/nextjs-monorepo-example/pull/3338

But to be honest, I recommend to create your own docker setup till I find time to improve it here.
