### ISSUE TITLE
add prettier for formatting and remove prettier for linting

### ISSUE THREAD

**Issue by bryce-larson** [belgattitude/nextjs-monorepo-example#3920]
Consider removing prettier as part of eslint and add it the package script for formatting, it is not a linter.

https://prettier.io/docs/en/integrating-with-linters.html
https://prettier.io/docs/en/comparison.html

For example running `yarn run g:lint`

With prettier lintting rule:
```
[nextjs-app]: Rule                                   | Time (ms) | Relative
[nextjs-app]: :--------------------------------------|----------:|--------:
[nextjs-app]: prettier/prettier                      |   592.110 |    23.5%
[nextjs-app]: import/default                         |   382.082 |    15.2%
[nextjs-app]: import/no-duplicates                   |   330.011 |    13.1%
[nextjs-app]: tailwindcss/classnames-order           |   294.505 |    11.7%
[nextjs-app]: tailwindcss/no-contradicting-classname |   150.598 |     6.0%
[nextjs-app]: sonarjs/no-ignored-return              |   148.545 |     5.9%
[nextjs-app]: import/no-unresolved                   |   117.598 |     4.7%
[nextjs-app]: import/no-named-as-default             |   104.360 |     4.1%
[nextjs-app]: tailwindcss/enforces-shorthand         |   101.104 |     4.0%
[nextjs-app]: @typescript-eslint/naming-convention   |    40.204 |     1.6%
```

Without prettier lintting rule:
```
[nextjs-app]: Rule                                   | Time (ms) | Relative
[nextjs-app]: :--------------------------------------|----------:|--------:
[nextjs-app]: import/default                         |   360.500 |    21.5%
[nextjs-app]: import/no-duplicates                   |   283.216 |    16.9%
[nextjs-app]: tailwindcss/classnames-order           |   216.061 |    12.9%
[nextjs-app]: sonarjs/no-ignored-return              |   151.779 |     9.1%
[nextjs-app]: tailwindcss/no-contradicting-classname |   135.110 |     8.1%
[nextjs-app]: tailwindcss/enforces-shorthand         |    97.479 |     5.8%
[nextjs-app]: import/no-named-as-default             |    96.537 |     5.8%
[nextjs-app]: import/no-unresolved                   |    69.346 |     4.1%
[nextjs-app]: @typescript-eslint/naming-convention   |    40.471 |     2.4%
[nextjs-app]: import/order                           |    20.577 |     1.2%
```

**Comment by belgattitude** [comment]
Hey @bryce-larson nice that you point this out.

In my experience what makes eslint and prettier fast is actually starting from a warm (or as warm as possible) cache.

But you're right, separating prettier and eslint rather than using the [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and cleanup incompatible rules with [eslint-prettier-config](https://github.com/prettier/eslint-config-prettier) will be globally faster. 

But in that case we'll have to run 2 separate steps (one for prettier, one for eslint) and handle proper caching for 2 tools instead of one... and that's a bit painful

As an example:

```json
{
  "scripts": {
    "prettier-check": "run --top-level prettier --check --cache --cache-location=\"../../.cache/prettier/exception.prettiercache\" --config ../../.prettierrc.js --ignore-path ../../.prettierignore \"./**/*.{js,jsx,cjs,mjs,ts,tsx,mts,md,mdx,json,css,scss,less}\"",
    "prettier-fix": "run --top-level prettier --write --cache --cache-location=\"../../.cache/prettier/exception.prettiercache\" --config ../../.prettierrc.js --ignore-path ../../.prettierignore \"./**/*.{js,jsx,cjs,mjs,ts,tsx,mts,md,mdx,json,css,scss,less}\"",
    "lint": "eslint . --ext .ts,.tsx,.js,.jsx,.mjs,.cjs,.mts,.cts --cache --cache-location ../../.cache/eslint/exception.eslintcache",
    "lint-timing": "cross-env TIMING=1 run lint",
  }
}
``` 

Some ci steps:

```yaml
     
      ## Here an action cache to save the global  .cache folder (will need an invalidation key based on date to
      ## avoid growing over time

      - name: 🔬 Prettier checks
        run: yarn workspaces foreach -tv --from '@httpx/*' --no-private run prettier-check
      - name: 🔬 ESLint checks
        run: yarn workspaces foreach -tv --from '@httpx/*' --no-private run lint
```

> PS: same to add for lint-staged / husky, etc...


That said I use both approaches in multiple repos... and globally I'd say no significant difference in the approaches (when cache is in place). The key is that when using the slower [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) approach, the setup part is easier (only one tool). 

As this repo is an example, I would keep it simple for now...

If you like, you can have a look to my day to day eslint configs... In that one, you can choose which mode you prefer:

- https://github.com/belgattitude/shared-dx/tree/main/packages/eslint-config-bases#usage

There's also a lot to say regarding caches: 

- many tools tried to store their caches in node_modules and reverting back due to monorepo issues (prettier, ...)
- nextjs stores them in .next folder (inluding eslint caches...)... helps also with vercel.
- jest will use the cache from config...

I'm still waiting a bit to see if it's worth to create some tooling to align those difference (ie: eslint flat configs) and if some idea reduce the setup, I'd gladly isolate prettier and eslint for every project.

**Comment by bryce-larson** [comment]
Cheers, thanks for taking the time to explain the reasoning.

**Comment by belgattitude** [comment]
Glad to hear

worth to mention: https://antfu.me/posts/why-not-prettier.  The author has good points imho. I'm also following the upcoming typescript-eslint v6: https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta/. It might help clarify stylistic vs typechecks.
